data-dir: /opt/pandoc
from: markdown
listings: true
dpi: 75
variables:
  lang: en
  fontsize: 10pt
  toc-own-page: true
  footnotes-pretty: true
  table-use-row-colors: true
  table-row-color: "333333"
  table-row-height: 142pt
  table-column-color: "333333"
  titlepage-background: 'Content/Media/Cover/CINO-Cover.pdf'

