template: eisvogel
pdf-engine: lualatex
data-dir: /opt/pandoc
listings: true
dpi: 300
toc: true
toc-depth: 2
columns: 2
from: markdown
to: pdf
variables:
  lang: de
  titlepage: true
  titlepage-color: '333333'
  titlepage-text-color: '333333'
  titlepage-rule-color: 'cccccc'
  titlepage-rule-height: 1
  titlepage-background: 'Content/Media/Cover/CINO-Cover.pdf'
  page-background: 'Content/Media/Cover/CINO-Body.pdf'
  fontsize: 10pt
  logo-width: 64mm
  book: false
  toc-own-page: true
  toc-depth: 2
  footnotes-pretty: true
  table-use-row-colors: true
  table-row-color: '333333'
  table-row-height: 142pt
  table-column-color: '333333'
  header-includes:
    - \hypersetup{
      colorlinks=true,
      allbordercolors={0 0 0},
      pdfborderstyle={/S/U/W 1},
      linkbordercolor=purple,
      linkcolor=purple,
      citecolor=gray,
      filecolor=purple,
      urlcolor=purple,
      pagebackref=true}
